name: MB Photography
analytics: {}
github: true
description: >-
  An exploration of our world, an effort to strip away misconception and look at
  our environments in an unassuming and whimsical way.
author:
  name: Miller Bradley
  url: millerbradley.com
  email: millerbradleyis@gmail.com
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
content: []
layout_spectrum: 1
color:
  lightness: 0.8309438
  brandColors:
    - '#1E170D'
    - '#A3927F'
    - '#806C55'
    - '#FFFFF2'
    - '#54AC52'
  saturation: 0.6087216
  brandStrength: 0
  rhythmicContrast: 0.03405014
content_rating:
  adult: false
typography_spectrum: 0.2885304
opengraph: {}
title: The Photographic Works Miller James Bradley
